version: '3.7'

services:

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test@123
      - MYSQL_DATABASE=dev_invest
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql       
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: redis:5.0.6
    restart: always
    ports: 
      - 6379:6379
  api:
    image: node:16.18.1-alpine3.15
    volumes:
      - ../:/dev-pay
    env_file: ../.env
    working_dir: /dev-pay
    depends_on:
      - redis
      - database
    restart: always
    environment:
      - SECRET_KEY=fakeSecretKey
      - HOST_PORT=3333
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=test@123
      - DB_NAME=dev_invest
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL='mysql://root:test@123@database:3306/dev_invest'
    ports:
      - 3333:3333
    command: ash -c "rm -rf ./node_modules && npm install && npm run dev"