version: '3.7'

services:

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test@123
      - MYSQL_DATABASE=dev_invest
    ports:
      - 3306:3306
    command: --init-file /data/application/database-init.sql       
    volumes:
      - ../development/database-init.sql:/data/application/database-init.sql

  redis:
    image: redis:5.0.6
    restart: always
    ports: 
      - 6379:6379

  api:
    image: node:16.18.1-alpine3.15
    volumes:
      - ../:/dev-pay
    env_file: ../.env
    working_dir: /dev-pay
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    restart: always
    ports:
      - 3333:3333
    command: ash -c "sleep 1 && npm install && npm run dev"